// JSON toolbox config for CoronaEngine custom blocks and standard Blockly blocks.
const block = (type, extra = {}) => ({ kind: 'block', type, ...extra });

export const TOOLBOX_CONFIG = {
  kind: 'categoryToolbox',
  scrollbars: true,
  contents: [
    {
      kind: 'category',
      name: "\u4e8b\u4ef6",
      categorystyle: 'event_category',
      contents: [
        block('event_gameStart'),
        block('event_keyboard'),
        block('event_keyboard_combo'),
        block('event_mouse_click'),
        block('event_mouse_move'),
        block('event_mouse_wheel'),
        block('event_mouse_contextmenu'),
        block('event_RB'),
        block('event_broadcast'),
        block('event_broadcastWait'),
        block('node_when_enter', { nodeGraphOnly: true }),
        block('node_while_active', { nodeGraphOnly: true }),
        block('node_when_exit', { nodeGraphOnly: true }),
      ],
    },
    {
      kind: 'category',
      name: "\u63a7\u5236",
      categorystyle: 'control_category',
      contents: [
        block('control_run_project_script'),
        block('control_wait'),
        block('control_wait2'),
        block('control_for'),
        block('control_forX'),
        block('control_until'),
        block('control_if'),
        block('control_else'),
        block('control_stop'),
        block('control_cloneStart'),
        block('control_clone'),
        block('control_cloneDEL'),
        block('control_senceSet'),
        block('control_nextSence'),
        block('control_restart_level'),
        block('control_cooldown_ready'),
        block('control_start_cooldown'),
        block('control_reset_cooldown'),
      ],
    },
    {
      kind: 'category',
      name: "\u6761\u4ef6",
      categorystyle: 'condition_category',
      contents: [
        block('logic_boolean'),
        block('logic_compare'),
        block('logic_operation'),
        block('logic_negate'),
        block('math_number'),
        block('math_arithmetic'),
        block('variable_get'),
        block('variable_exists'),
        block('detect_touch'),
        block('detect_not_touch'),
        block('detect_touch_any'),
        block('detect_touch_tag'),
        block('detect_touch_started'),
        block('detect_touch_tag_started'),
        block('detect_object_exists'),
        block('detect_object_not_exists'),
        block('detect_keyboard1'),
        block('detect_keyboard0'),
        block('detect_mouse1'),
        block('detect_mouse0'),
        block('detect_mouse_left_half'),
        block('detect_mouse_right_half'),
        block('detect_mouse_x_ratio'),
        block('detect_ground_below'),
        block('detect_no_ground_below'),
        block('detect_inside_axis'),
        block('detect_outside_axis'),
        block('detect_inside_box'),
        block('detect_position_near'),
        block('detect_raycast'),
        block('detect_raycast_hit_tag'),
        block('detect_last_collision_axis'),
        block('ui_countdown_finished'),
        block('ui_game_state'),
        block('ui_score'),
        block('ui_lives'),
        block('ui_countdown_left'),
      ],
    },
    {
      kind: 'category',
      name: "\u8fd0\u52a8",
      categorystyle: 'motion_category',
      contents: [
        block('engine_move'),
        block('engine_rotateX'),
        block('engine_rotateY'),
        block('engine_rotateZ'),
        block('engine_face'),
        block('engine_moveto'),
        block('engine_movetoXYZ'),
        block('engine_movetoXYZtime'),
        block('engine_Xset'),
        block('engine_Yset'),
        block('engine_Zset'),
        block('engine_Xadd'),
        block('engine_Yadd'),
        block('engine_Zadd'),
        block('engine_X'),
        block('engine_Y'),
        block('engine_Z'),
        block('engine_rotationX'),
        block('engine_rotationY'),
        block('engine_rotationZ'),
        block('object_set_position'),
        block('object_move_direction'),
        block('object_get_x'),
        block('object_get_y'),
        block('object_get_z'),
        block('object_move_tag'),
        block('object_clamp_axis'),
      ],
    },
    {
      kind: 'category',
      name: "\u7269\u7406",
      categorystyle: 'physics_category',
      contents: [
        block('engine_set_velocity'),
        block('engine_set_velocity_axis'),
        block('engine_get_velocity'),
        block('engine_apply_impulse'),
        block('engine_stop_motion'),
        block('engine_set_gravity'),
        block('engine_jump'),
        block('engine_bounce_axis'),
        block('engine_bounce_last_collision'),
        block('object_set_native_physics'),
        block('object_set_logical_collision'),
        block('object_logical_collision_enabled'),
      ],
    },
    {
      kind: 'category',
      name: "\u6444\u50cf\u673a",
      categorystyle: 'camera_category',
      contents: [
        block('camera_lock_mouse'),
        block('camera_unlock_mouse'),
        block('camera_mouse_dx'),
        block('camera_mouse_dy'),
        block('camera_set_fov'),
        block('camera_follow_object'),
        block('camera_third_person_orbit'),
        block('camera_first_person_follow'),
        block('camera_raycast'),
        block('camera_raycast_object'),
      ],
    },
    {
      kind: 'category',
      name: "\u5916\u89c2",
      categorystyle: 'appearance_category',
      contents: [
        block('appearance_cartoonSet'),
        block('appearance_nextCartoon'),
        block('appearance_playCartoon'),
        block('appearance_stopCartoon'),
        block('appearance_resetCartoon'),
        block('appearance_sizeAdd'),
        block('appearance_sizeSet'),
        block('appearance_show'),
        block('appearance_hide'),
        block('appearance_cartoon'),
        block('appearance_size'),
        block('appearance_set_color'),
        block('appearance_set_alpha'),
      ],
    },
    {
      kind: 'category',
      name: "\u5bf9\u8c61",
      categorystyle: 'object_category',
      contents: [
        block('object_reference'),
        block('object_hide'),
        block('object_show'),
        block('object_delete'),
        block('object_delete_last_touched'),
        block('object_exists'),
        block('object_set_tag'),
        block('object_tag_numbered_range'),
        block('object_count_tag'),
        block('object_spawn'),
        block('object_spawn_tag'),
        block('object_delete_raycast_hit'),
        block('object_save_checkpoint'),
        block('object_restore_checkpoint'),
        block('object_reset_crossed_once'),
      ],
    },
    {
      kind: 'category',
      name: "\u4fa6\u6d4b",
      categorystyle: 'detect_category',
      contents: [
        block('detect_touch'),
        block('detect_not_touch'),
        block('detect_touch_any'),
        block('detect_not_touch_any'),
        block('detect_touch_tag'),
        block('detect_not_touch_tag'),
        block('detect_touch_started'),
        block('detect_touch_tag_started'),
        block('detect_last_touch_object'),
        block('detect_object_exists'),
        block('detect_object_not_exists'),
        block('detect_distance'),
        block('detect_ground_below'),
        block('detect_no_ground_below'),
        block('detect_passed_x'),
        block('detect_passed_z'),
        block('detect_crossed_x_once'),
        block('detect_crossed_z_once'),
        block('detect_outside_axis'),
        block('detect_inside_axis'),
        block('detect_inside_box'),
        block('detect_position_near'),
        block('detect_keyboard1'),
        block('detect_keyboard0'),
        block('detect_mouse1'),
        block('detect_mouse0'),
        block('detect_mouse_left_half'),
        block('detect_mouse_right_half'),
        block('detect_mouse_x_ratio'),
        block('detect_ask_answer'),
        block('detect_attribute'),
        block('detect_raycast'),
        block('detect_raycast_distance'),
        block('detect_raycast_object'),
        block('detect_raycast_point'),
        block('detect_raycast_hit_tag'),
        block('detect_last_collision_axis'),
        block('detect_last_collision_normal_x'),
        block('detect_last_collision_normal_y'),
        block('detect_last_collision_normal_z'),
        block('detect_mouse_pick_object'),
        block('detect_mouse_pick_hit_tag'),
      ],
    },
    {
      kind: 'category',
      name: "\u754c\u9762",
      categorystyle: 'ui_category',
      contents: [
        block('ui_set_score'),
        block('ui_add_score'),
        block('ui_score'),
        block('ui_set_lives'),
        block('ui_add_lives'),
        block('ui_lives'),
        block('ui_set_countdown'),
        block('ui_countdown_left'),
        block('ui_countdown_elapsed'),
        block('ui_countdown_finished'),
        block('ui_game_state'),
        block('ui_game_win'),
        block('ui_game_over'),
      ],
    },
    {
      kind: 'category',
      name: "\u97f3\u6548",
      categorystyle: 'audio_category',
      contents: [
        block('audio_play'),
        block('audio_loop'),
        block('audio_stop'),
        block('audio_stop_all'),
      ],
    },
    {
      kind: 'category',
      name: "\u5168\u5c40\u53d8\u91cf",
      categorystyle: 'variable_category',
      contents: [
        block('variable_define'),
        block('variable_get'),
        block('variable_exists'),
        block('variable_set'),
        block('variable_add'),
        block('variable_show'),
        block('variable_hide'),
      ],
    },
    {
      kind: 'category',
      name: "\u5217\u8868",
      categorystyle: 'list_category',
      contents: [
        block('list_define'),
        block('list_add_named'),
        block('list_insert_named'),
        block('list_remove_index_named'),
        block('list_remove_value_named'),
        block('list_clear_named'),
        block('list_item_named'),
        block('list_length_named'),
        block('list_contains_named'),
        block('list_show'),
        block('list_hide'),
        block('lists_create_empty'),
        block('lists_create_with'),
        block('lists_repeat'),
        block('lists_length'),
        block('lists_isEmpty'),
        block('lists_indexOf'),
        block('lists_getIndex'),
        block('lists_setIndex'),
        block('lists_getSublist'),
        block('lists_reverse'),
        block('lists_sort'),
        block('lists_split'),
      ],
    },
    {
      kind: 'category',
      name: "\u8fd0\u7b97",
      categorystyle: 'math_category',
      contents: [
        block('logic_boolean'),
        block('logic_compare'),
        block('logic_operation'),
        block('logic_negate'),
        block('logic_null'),
        block('logic_ternary'),
        block('math_number'),
        block('math_arithmetic'),
        block('math_single'),
        block('math_trig'),
        block('math_constant'),
        block('math_number_property'),
        block('math_round'),
        block('math_on_list'),
        block('math_modulo'),
        block('math_constrain'),
        block('math_random_int'),
        block('math_random_float'),
        block('math_atan2'),
      ],
    },
    {
      kind: 'category',
      name: "\u6587\u672c",
      categorystyle: 'text_category',
      contents: [
        block('text'),
        block('text_join'),
        block('text_append'),
        block('text_length'),
        block('text_isEmpty'),
        block('text_indexOf'),
        block('text_charAt'),
        block('text_getSubstring'),
        block('text_changeCase'),
        block('text_trim'),
        block('text_count'),
        block('text_replace'),
        block('text_reverse'),
        block('text_print'),
        block('text_prompt_ext'),
      ],
    },
    {
      kind: 'category',
      name: "\u51fd\u6570",
      categorystyle: 'function_category',
      contents: [
        block('procedures_defnoreturn'),
        block('procedures_defreturn'),
        block('procedures_callnoreturn'),
        block('procedures_callreturn'),
        block('procedures_ifreturn'),
      ],
    },
    {
      kind: 'category',
      name: "\u73a9\u6cd5\u6a21\u677f",
      categorystyle: 'gameplay_category',
      contents: [
        block('engine_set_game_speed'),
        block('engine_get_game_speed'),
        block('object_move_to_lane'),
        block('object_move_to_lane_smooth'),
        block('object_lane_index'),
        block('object_set_random_position'),
        block('object_spawn_random_box'),
        block('object_scatter_tag'),
        block('object_recycle_tag_axis'),
        block('object_reset_tag'),
        block('object_count_active_tag'),
        block('object_set_tag_velocity_axis'),
        block('object_randomize_mouse_pick'),
        block('object_delete_mouse_pick'),
        block('object_third_person_move'),
        block('object_arcade_jump'),
        block('object_collect_touching_tag'),
        block('object_breakout_reset_round'),
        block('object_breakout_paddle_control'),
        block('object_breakout_step'),
        block('object_first_person_move'),
        block('combat_set_tag_health'),
        block('combat_melee_attack'),
        block('combat_enemy_chase_tag'),
        block('combat_enemy_contact_damage'),
        block('combat_alive_count'),
      ],
    },
  ],
};

const CATEGORY_KEYS = {
  "\u4e8b\u4ef6": 'blocklyToolbox.event',
  "\u63a7\u5236": 'blocklyToolbox.control',
  "\u6761\u4ef6": 'blocklyToolbox.condition',
  "\u8fd0\u52a8": 'blocklyToolbox.motion',
  "\u7269\u7406": 'blocklyToolbox.physics',
  "\u6444\u50cf\u673a": 'blocklyToolbox.camera',
  "\u5916\u89c2": 'blocklyToolbox.appearance',
  "\u5bf9\u8c61": 'blocklyToolbox.object',
  "\u4fa6\u6d4b": 'blocklyToolbox.detect',
  "\u754c\u9762": 'blocklyToolbox.ui',
  "\u97f3\u6548": 'blocklyToolbox.audio',
  "\u5168\u5c40\u53d8\u91cf": 'blocklyToolbox.globalVariable',
  "\u5217\u8868": 'blocklyToolbox.list',
  "\u8fd0\u7b97": 'blocklyToolbox.math',
  "\u6587\u672c": 'blocklyToolbox.text',
  "\u51fd\u6570": 'blocklyToolbox.functions',
  "\u73a9\u6cd5\u6a21\u677f": 'blocklyToolbox.gameplay',
};

export function createToolboxConfig(t = (key) => key) {
  const clone = structuredClone(TOOLBOX_CONFIG);
  for (const category of clone.contents || []) {
    if (category.kind === 'category') {
      category.contents = (category.contents || []).filter((item) => !item.nodeGraphOnly);
      if (CATEGORY_KEYS[category.name]) category.name = t(CATEGORY_KEYS[category.name]);
    }
  }
  return clone;
}
