
set(_CORONA_RESOURCE_IS_TOP_LEVEL OFF)
if(DEFINED CORONA_RESOURCE_ROOT AND CMAKE_SOURCE_DIR STREQUAL CORONA_RESOURCE_ROOT)
    set(_CORONA_RESOURCE_IS_TOP_LEVEL ON)
endif()

option(CORONA_RESOURCE_BUILD_EXAMPLES "Build CoronaResource examples" ${_CORONA_RESOURCE_IS_TOP_LEVEL})
option(CORONA_RESOURCE_BUILD_TESTS "Build CoronaResource tests" ${_CORONA_RESOURCE_IS_TOP_LEVEL})

unset(_CORONA_RESOURCE_IS_TOP_LEVEL)
